# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [3]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [5]:
A = np.arange(1, 16).reshape(3,5)

In [6]:
A.shape

(3, 5)

### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [8]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [9]:
D =B @ C
print(D)

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


In [10]:
D = B - C
print(D)

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]


In [11]:
D = B + C
print(D)

[[ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [13]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
C = np.exp(B)
print(C)

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]


In [15]:
print(np.min(B))
print(np.min(B, axis=0))
print(np.min(B, axis=1))

1
[1 2 3]
[1 4 7]


In [16]:
print(np.argmin(B))
print(np.argmin(B, axis=1))

0
[0 0 0]


In [17]:
print(np.sum(B))
print(np.mean(B, axis=0))
print(np.median(B, axis=0))

45
[4. 5. 6.]
[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [19]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [20]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [22]:
#This means you get only the row specified. In this case the second row since the first row have index 0

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [24]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [25]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [26]:
for x in np.nditer(A):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [28]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [29]:
#The array is split into 2 blocks with 3 rows. The -1 lets numpy decide the number of columns

# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [34]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [36]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [37]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [40]:
def add_mult_matrices(v1,v2, action):
    if isinstance(v1, np.ndarray):
        if isinstance(v2, np.ndarray):
            if v1.shape[0] == v2.shape[1]:
                if action == "add":
                    return v1 + v2
                elif action == "multiply":
                    return v1 @ v2
                else:
                    return "You have to use add or multiply as action"     
            else:
                return "The sizes of the input isn't conform"
        else:
            return "Second input isn't a numpy array"
    else:
        return "First input isn't a numpy array"

v1 = np.array([[1, 2], [3, 4]])
v2 = np.array([[1, 2], [3, 4]])
#v2 = np.array([[1], [1]])
#v1 = "Test"

add_mult_matrices(v1, v2,'multiply')


array([[ 7, 10],
       [15, 22]])

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [42]:
print("--  Uppgift 10.1.1  --")

x = np.array([[3,4]])
print(f" a: Vektorn x har dimensionen 1x2 (en rad och två kolumner)")

b = x * 5
print(f" b: 5x {b}")

c = x * 3
print(f" c: 3x {c}")

d = (x * 5) + (x * 3)
print(f" d: 5x + 3x {d}")

e = x * 8
print(f" e: 8x {e}")

f = (x * 4) - x
print(f" f: 4x - x {f}")

g = np.transpose(x)
print(f" g: x trasponerad {g} har dimensionen 2 x 1 två rader och en kolumn")

print(f" h: vet ej")

i = np.linalg.norm(x)
print(f" i: norm av x = {i}")

--  Uppgift 10.1.1  --
 a: Vektorn x har dimensionen 1x2 (en rad och två kolumner)
 b: 5x [[15 20]]
 c: 3x [[ 9 12]]
 d: 5x + 3x [[24 32]]
 e: 8x [[24 32]]
 f: 4x - x [[ 9 12]]
 g: x trasponerad [[3]
 [4]] har dimensionen 2 x 1 två rader och en kolumn
 h: vet ej
 i: norm av x = 5.0


In [43]:
print("--  Uppgift 10.1.2  --")

v = np.array([3, 7, 0, 11])
print(f" a: {v} Vektorn x har dimensionen 4x1 (fyra rad och en kolumn)")

b = v * 2
print(f" b: 2v {b}")

c = (v * 5) + (v * 2)
print(f" c: 5v + 2v {c}")

d = (v * 4) - (v * 2)
print(f" d: 4v - 2v {d}")

e = np.transpose(v)
print(f" g: v trasponerad {e} har dimensionen 1 x 4 en rader och fyra kolumner")

f = np.linalg.norm(v)
print(f" f: norm av v = {f}")

--  Uppgift 10.1.2  --
 a: [ 3  7  0 11] Vektorn x har dimensionen 4x1 (fyra rad och en kolumn)
 b: 2v [ 6 14  0 22]
 c: 5v + 2v [21 49  0 77]
 d: 4v - 2v [ 6 14  0 22]
 g: v trasponerad [ 3  7  0 11] har dimensionen 1 x 4 en rader och fyra kolumner
 f: norm av v = 13.379088160259652


In [44]:
print("--  Uppgift 10.1.3  --")

v1 = np.array([[4,3,1,5]])
v2 = np.array([[2,3,1,1]])

a = np.linalg.norm(v1)
print(f" a: norm av v1 = {a}")

b = np.linalg.norm(v1 - v2)
    #v3 = v1 - v2
    #print(v3)
    #v4 = np.linalg.norm(v3)
    #print(v4) 
print(f" b: norm av v1 - v2 = {b}")

--  Uppgift 10.1.3  --
 a: norm av v1 = 7.14142842854285
 b: norm av v1 - v2 = 4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [46]:
print("--  Uppgift 10.2.1  --")

A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])
C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])
E = np.array([[1, 2]])
I = np.array([[1, 0], [0, 1]])

a = A * 2
print(f" a: \n {a}")
b = B - (A * 2)
print(f" b: \n {b}")
c = (C * 3) - (E * 2)
print(f" c: \n {c}")
d = (D * 2) - (C * 3)
print(f" d: \n {d}")
e = np.transpose(D) + (D * 2)
print(f" e: \n {e}")
f = (np.transpose(C) * 2) + (np.transpose(D) * 2)
print(f" f: \n {f}")
#g = np.transpose(A) - B
print(f" g: \n The matrices dont have the same number of folumns and rows")
#h = A @ C
print(f" h: \n The first matric have three columns but the second only have two rows")
i = C @ D
print(f" i: \n {i}")
j = C @ B
print(f" j: \n {j}")
k = C @ I
print(f" k: \n {k}")
l =  A @ np.transpose(B) 
print(f" l: \n {l}")

--  Uppgift 10.2.1  --
 a: 
 [[ 4  2 -2]
 [ 2 -2  2]]
 b: 
 [[ 0 -4  3]
 [ 0 -2 -4]]
 c: 
 [[ 1  2]
 [ 4 -1]]
 d: 
 [[3 2]
 [2 3]]
 e: 
 [[ 9 12]
 [12  9]]
 f: 
 [[ 8 12]
 [12  8]]
 g: 
 The matrices dont have the same number of folumns and rows
 h: 
 The first matric have three columns but the second only have two rows
 i: 
 [[11 10]
 [10 11]]
 j: 
 [[  8 -10  -3]
 [ 10  -8   0]]
 k: 
 [[1 2]
 [2 1]]
 l: 
 [[5 2]
 [7 4]]


In [47]:
print("--  Uppgift 10.2.2  --")

A = np.array([[2, 3, 4], [5, 4, 1]])

a = A @ np.transpose(A)
print(f" {a}")


--  Uppgift 10.2.2  --
 [[29 26]
 [26 42]]


In [48]:
print("--  Uppgift 10.2.3  --")

A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])

ab = A @ B
print(f"  A * B: \n {ab}")
ac = A @ C
print(f"  A * C: \n {ac}")

--  Uppgift 10.2.3  --
  A * B: 
 [[ 4  7]
 [ 8 14]]
  A * C: 
 [[ 4  7]
 [ 8 14]]


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [51]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)


[0 1 2 3]
[2 3]


In [52]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [53]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
